// Code generated by protoc-gen-go. DO NOT EDIT.
// source: micro.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	micro.proto

It has these top-level messages:
	User
	ModifyUserReq
	ModifyUserRep
	SelectUserReq
	SelectUserRep
	DeletetUserReq
	DeletetUserRep
	InsertUserReq
	InsertUserRep
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id      int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=Address" json:"Address,omitempty"`
	Phone   string `protobuf:"bytes,4,opt,name=Phone" json:"Phone,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ModifyUserReq struct {
	Id      int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=Address" json:"Address,omitempty"`
	Phone   string `protobuf:"bytes,4,opt,name=Phone" json:"Phone,omitempty"`
}

func (m *ModifyUserReq) Reset()                    { *m = ModifyUserReq{} }
func (m *ModifyUserReq) String() string            { return proto.CompactTextString(m) }
func (*ModifyUserReq) ProtoMessage()               {}
func (*ModifyUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ModifyUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ModifyUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModifyUserReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ModifyUserReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ModifyUserRep struct {
}

func (m *ModifyUserRep) Reset()                    { *m = ModifyUserRep{} }
func (m *ModifyUserRep) String() string            { return proto.CompactTextString(m) }
func (*ModifyUserRep) ProtoMessage()               {}
func (*ModifyUserRep) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type SelectUserReq struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *SelectUserReq) Reset()                    { *m = SelectUserReq{} }
func (m *SelectUserReq) String() string            { return proto.CompactTextString(m) }
func (*SelectUserReq) ProtoMessage()               {}
func (*SelectUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SelectUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SelectUserRep struct {
	Users *User `protobuf:"bytes,1,opt,name=users" json:"users,omitempty"`
}

func (m *SelectUserRep) Reset()                    { *m = SelectUserRep{} }
func (m *SelectUserRep) String() string            { return proto.CompactTextString(m) }
func (*SelectUserRep) ProtoMessage()               {}
func (*SelectUserRep) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SelectUserRep) GetUsers() *User {
	if m != nil {
		return m.Users
	}
	return nil
}

type DeletetUserReq struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeletetUserReq) Reset()                    { *m = DeletetUserReq{} }
func (m *DeletetUserReq) String() string            { return proto.CompactTextString(m) }
func (*DeletetUserReq) ProtoMessage()               {}
func (*DeletetUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeletetUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeletetUserRep struct {
}

func (m *DeletetUserRep) Reset()                    { *m = DeletetUserRep{} }
func (m *DeletetUserRep) String() string            { return proto.CompactTextString(m) }
func (*DeletetUserRep) ProtoMessage()               {}
func (*DeletetUserRep) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type InsertUserReq struct {
	Id      int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=Address" json:"Address,omitempty"`
	Phone   string `protobuf:"bytes,4,opt,name=Phone" json:"Phone,omitempty"`
}

func (m *InsertUserReq) Reset()                    { *m = InsertUserReq{} }
func (m *InsertUserReq) String() string            { return proto.CompactTextString(m) }
func (*InsertUserReq) ProtoMessage()               {}
func (*InsertUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *InsertUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InsertUserReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InsertUserReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type InsertUserRep struct {
	Id      int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=Address" json:"Address,omitempty"`
	Phone   string `protobuf:"bytes,4,opt,name=Phone" json:"Phone,omitempty"`
}

func (m *InsertUserRep) Reset()                    { *m = InsertUserRep{} }
func (m *InsertUserRep) String() string            { return proto.CompactTextString(m) }
func (*InsertUserRep) ProtoMessage()               {}
func (*InsertUserRep) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *InsertUserRep) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertUserRep) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InsertUserRep) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InsertUserRep) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*ModifyUserReq)(nil), "pb.ModifyUserReq")
	proto.RegisterType((*ModifyUserRep)(nil), "pb.ModifyUserRep")
	proto.RegisterType((*SelectUserReq)(nil), "pb.SelectUserReq")
	proto.RegisterType((*SelectUserRep)(nil), "pb.SelectUserRep")
	proto.RegisterType((*DeletetUserReq)(nil), "pb.DeletetUserReq")
	proto.RegisterType((*DeletetUserRep)(nil), "pb.DeletetUserRep")
	proto.RegisterType((*InsertUserReq)(nil), "pb.InsertUserReq")
	proto.RegisterType((*InsertUserRep)(nil), "pb.InsertUserRep")
}

func init() { proto.RegisterFile("micro.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0x9b, 0x98, 0xf8, 0x31, 0xa1, 0x55, 0x07, 0x0f, 0x21, 0x07, 0x0d, 0x7b, 0xea, 0x29,
	0x42, 0x2d, 0x78, 0x16, 0xbc, 0x78, 0x10, 0x24, 0xc5, 0x8b, 0x37, 0x93, 0x1d, 0x71, 0xa1, 0xcd,
	0xae, 0xbb, 0x51, 0xf0, 0x1f, 0xfb, 0x33, 0x64, 0x37, 0x4a, 0xba, 0x0d, 0x3d, 0xe6, 0x96, 0x79,
	0xf3, 0xce, 0x3c, 0xcc, 0xc7, 0x42, 0xb2, 0x11, 0xb5, 0x96, 0x85, 0xd2, 0xb2, 0x95, 0x18, 0xaa,
	0x8a, 0xbd, 0x40, 0xf4, 0x6c, 0x48, 0xe3, 0x0c, 0x42, 0xc1, 0xd3, 0x20, 0x0f, 0xe6, 0x71, 0x19,
	0x0a, 0x8e, 0x08, 0x51, 0xf3, 0xba, 0xa1, 0x34, 0xcc, 0x83, 0xf9, 0x49, 0xe9, 0xbe, 0x31, 0x85,
	0xa3, 0x3b, 0xce, 0x35, 0x19, 0x93, 0x1e, 0x38, 0xf9, 0x3f, 0xc4, 0x0b, 0x88, 0x9f, 0xde, 0x65,
	0x43, 0x69, 0xe4, 0xf4, 0x2e, 0x60, 0x35, 0x4c, 0x1f, 0x25, 0x17, 0x6f, 0xdf, 0x96, 0x50, 0xd2,
	0xc7, 0x28, 0x90, 0x53, 0x1f, 0xa2, 0xd8, 0x15, 0x4c, 0x57, 0xb4, 0xa6, 0xba, 0xdd, 0x43, 0x65,
	0xd7, 0xbe, 0x41, 0xe1, 0x25, 0xc4, 0x9f, 0x86, 0xb4, 0x71, 0x9e, 0x64, 0x71, 0x5c, 0xa8, 0xaa,
	0x70, 0xff, 0x3a, 0x99, 0xe5, 0x30, 0xbb, 0xa7, 0x35, 0xb5, 0xb4, 0xb7, 0xe4, 0xd9, 0x8e, 0x43,
	0xd9, 0xde, 0x1f, 0x1a, 0x43, 0xba, 0x1d, 0xb3, 0xf7, 0x1d, 0x88, 0x1a, 0x03, 0xb2, 0xf8, 0x09,
	0x20, 0xb1, 0xf5, 0x57, 0xa4, 0xbf, 0x44, 0x4d, 0xb8, 0x04, 0xe8, 0xa1, 0x78, 0x6e, 0x87, 0xe5,
	0x75, 0x9a, 0x0d, 0x24, 0xc5, 0x26, 0x78, 0x0b, 0xc9, 0xd6, 0x84, 0x10, 0xad, 0xc7, 0x1f, 0x6a,
	0x36, 0xd4, 0x6c, 0xe2, 0x12, 0xa0, 0xdf, 0x56, 0x87, 0xf3, 0xd6, 0x9b, 0x0d, 0xa4, 0xbf, 0xac,
	0xfe, 0x2a, 0xba, 0x2c, 0xef, 0x14, 0xb3, 0x81, 0xa4, 0xd8, 0xa4, 0x3a, 0x74, 0xef, 0xe2, 0xe6,
	0x37, 0x00, 0x00, 0xff, 0xff, 0xac, 0xd0, 0x98, 0x41, 0x26, 0x03, 0x00, 0x00,
}
